grafana:
  adminPassword: changeme
  ingress:
    annotations: 
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    enabled: true
    hosts: 
      - grafana.repostexchange.com

kubelet:
  namespace: prometheus-operator

prometheus:
  prometheusSpec:
    retention: 21d

prometheusOperator:
  kubeletService:
    namespace: prometheus-operator
